exclude: 'docs|node_modules|migrations|.git|.tox|.venv'
default_stages: [commit]
fail_fast: true

repos:
  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
    -   id: autoflake
        args:
            - --in-place
            - --remove-all-unused-imports
            - --expand-star-imports
            - --remove-duplicate-keys
            - --remove-unused-variables

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
      - id: black

  # - repo: https://github.com/timothycrosley/isort
  #   rev: 5.11.0
  #   hooks:
  #     - id: isort

  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        args: ['--config=setup.cfg']
        additional_dependencies: [flake8-isort]

  - repo: local
    hooks:
      - id: system
        name: Pylint
        entry: poetry run pylint main.py
        pass_filenames: false
        language: system

  - repo: local
    hooks:
      - id: pytest-cov
        name: pytest-cov
        entry: poetry run pytest --cov
        language: system
        pass_filenames: false
        always_run: true

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.0
    hooks:
      - id: bandit
        language_version: python3
        args:
        - -s
        - B404,B603
